---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nord-deployment
  labels:
    app: my-app
  annotations:
    kubernetes.io/change-cause: The New Updated Version
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80
