apiVersion: v1
kind: Pod
metadata:
 name: app1
 labels:
  name: app1
spec:
  containers:
  - name: nginx
    image: nginx
    args:
      - "--text=Hello Nagpur"
      - "--addr=:8080"
---
apiVersion: v1
kind: Pod
metadata:
 name: app2
 labels:
  name: app2
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    args:
      - "--text=Hello Indore"
      - "--addr=:8080"
